# Generated by Django 4.1.4 on 2022-12-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
